// <auto-generated />
using JoelHiltonMovies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JoelHiltonMovies.Migrations
{
    [DbContext(typeof(AddMovieContext))]
    partial class AddMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("JoelHiltonMovies.Models.AddMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Fantasy",
                            Director = "Chris Columbus",
                            Edited = false,
                            Rating = "PG",
                            Title = "Harry Potter and The Scorcere's Stone",
                            Year = "2001"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Fantasy",
                            Director = "Chris Columbus",
                            Edited = false,
                            Rating = "PG",
                            Title = "Harry Potter and The Chamber of Secrets",
                            Year = "2002"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Fantasy",
                            Director = "Alfonso Cuaron",
                            Edited = false,
                            Rating = "PG",
                            Title = "Harry Potter and The Prisoner of Azkaban",
                            Year = "2004"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
